jobs:
  - job: Build
    strategy:
      matrix:
        macOS_Mojave:
          imageName: 'macOS-10.14'
        macOS_Catalina:
          imageName: 'macOS-10.15'
    pool:
      vmImage: $(imageName)
    timeoutInMinutes: 120
    steps:
      - bash: |
          set -e
          brew update-reset
          sudo rm -rf /usr/local/include/node
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/kabel/homebrew-pecl"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          if [ -z "$SYSTEM_PULLREQUEST_TARGETBRANCH" ]; then export SYSTEM_PULLREQUEST_TARGETBRANCH="main"; fi
          if [ "$BUILD_REASON" = "PullRequest" ]; then export GITHUB_EVENT_NAME="pull_request"; fi
          export GITHUB_BASE_REF="$SYSTEM_PULLREQUEST_TARGETBRANCH"
          export GITHUB_SHA="$BUILD_SOURCEVERSION"
          export GITHUB_ACTIONS="fake"
          export GITHUB_REPOSITORY="$BUILD_REPOSITORY_NAME"
          export GITHUB_REF="$BUILD_SOURCEBRANCH"
          export HOMEBREW_GITHUB_ACTIONS=fake
          echo "==> Dumping Pipelines Vars..."
          echo "BUILD_REPOSITORY_NAME=$BUILD_REPOSITORY_NAME"
          echo "BUILD_SOURCEBRANCH=$BUILD_SOURCEBRANCH"
          echo "BUILD_SOURCEBRANCHNAME=$BUILD_SOURCEBRANCHNAME"
          echo "BUILD_SOURCEVERSION=$BUILD_SOURCEVERSION"
          echo "BUILD_REASON=$BUILD_REASON"
          echo "SYSTEM_PULLREQUEST_SOURCEBRANCH=$SYSTEM_PULLREQUEST_SOURCEBRANCH"
          echo "SYSTEM_PULLREQUEST_TARGETBRANCH=$SYSTEM_PULLREQUEST_TARGETBRANCH"
          echo
          TEST_PARAMS=""
          if [ "$BUILD_REASON" != "PullRequest" -a "$BUILD_SOURCEBRANCHNAME" = "$SYSTEM_PULLREQUEST_TARGETBRANCH" ]; then TEST_PARAMS="--only-tap-syntax"; fi
          brew test-bot --tap=kabel/pecl --root-url=https://kabel.jfrog.io/artifactory/bottles-pecl $TEST_PARAMS
        displayName: Run brew test-bot
      - task: CopyFiles@2
        displayName: 'Copy Bottle Files to Artifact Stage'
        inputs:
          Contents: '*.bottle.?(tar.gz|json)'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
        condition: succeededOrFailed()
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        condition: succeededOrFailed()
