parameters:
  name: macOS
  vmImage: macOS-10.14

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
    - bash: |
        set -e
        brew update
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/kabel/homebrew-pecl"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        if [ -z "$SYSTEM_PULLREQUEST_TARGETBRANCH" ]; then export SYSTEM_PULLREQUEST_TARGETBRANCH="origin/master"; fi
        brew test-bot --tap="kabel/pecl" --root-url=https://dl.bintray.com/kabel/bottles-pecl
      displayName: Run brew test-bot
    - task: CopyFiles@2
      displayName: 'Copy Bottle Files to Artifact Stage'
      inputs:
        Contents: '*.bottle.?(tar.gz|json)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      condition: succeededOrFailed()
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      condition: succeededOrFailed()
