parameters:
  name: macOS_Catalina
  vmImage: macOS-10.15

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
    - bash: |
        set -e
        brew update-reset
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/kabel/homebrew-pecl"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        if [ -z "$SYSTEM_PULLREQUEST_TARGETBRANCH" ]; then export SYSTEM_PULLREQUEST_TARGETBRANCH="master"; fi
        if [ "$BUILD_REASON" = "PullRequest" ]; then export GITHUB_EVENT_NAME="pull_request"; fi
        export GITHUB_BASE_REF="$SYSTEM_PULLREQUEST_TARGETBRANCH"
        export GITHUB_SHA="$BUILD_SOURCEVERSION"
        export GITHUB_ACTIONS="fake"
        export HOMEBREW_GITHUB_ACTIONS=fake
        brew test-bot --tap="kabel/pecl" --root-url=https://dl.bintray.com/kabel/bottles-pecl
      displayName: Run brew test-bot
    - task: CopyFiles@2
      displayName: 'Copy Bottle Files to Artifact Stage'
      inputs:
        Contents: '*.bottle.?(tar.gz|json)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      condition: succeededOrFailed()
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      condition: succeededOrFailed()
